sudo: required
services:
 - docker

before_install:
 - docker build -t idhamtsalasa/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true idhamtsalasa/react-test npm test

after_success:
 - docker build -t archvalkryn/multi-client ./client
 - docker build -t archvalkryn/multi-nginx ./nginx
 - docker build -t archvalkryn/multi-server ./server
 - docker build -t archvalkryn/multi-worker ./worker
# login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
 - docker push archvalkryn/multi-client
 - docker push archvalkryn/multi-nginx
 - docker push archvalkryn/multi-server
 - docker push archvalkryn/multi-worker

deploy:
 provider: elasticbeanstalk
 region: us-east-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-east-2-261637881759
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
