sudo:required
services:
 - docker

before_install:
 - docker build -t idhamtsalasa/multi-docker -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true idhamtsalasa/multi-docker npm test

after_success:
 - docker build -t idhamtsalasa/multi-client ./client
 - docker build -t idhamtsalasa/multi-nginx ./nginx
 - docker build -t idhamtsalasa/multi-server ./server
 - docker build -t idhamtsalasa/multi-worker ./worker
# login to docker CLI
 - echo "%DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
 - docker push idhamtsalasa/multi-client
 - docker push idhamtsalasa/multi-nginx
 - docker push idhamtsalasa/multi-server
 - docker push idhamtsalasa/multi-worker
